# Writes data generated by _extract_all_sprites.py to a generic binary format
import pickle
import struct

data_file='sprites-all-data'
with open(data_file, 'rb') as f:
	sprite_data = pickle.load(f)

out_data = bytearray()
out_data.extend(struct.pack('<H', len(sprite_data)))

for sprite_set, sprites in sprite_data.items():
	out_data.extend(sprite_set.encode('ascii'))
	out_data.extend(struct.pack('<H', len(sprites)))
	for sprite_name, box in sprites.items():
		out_data.extend(sprite_name.encode('ascii'))
		out_data.extend(struct.pack(
			'<hhHH',
		    box[0], box[1],
			box[2], box[3]
		))

with open('sprite-all-data.b', 'wb') as out:
	out.write(out_data)

